### ISSUE TITLE
Provide a link in error messages a la https://ipxe.org/err/...

### ISSUE THREAD

**Issue by huppmann** [haskell/error-messages#10]
This might be an entirely separate project but the way that iPXE produces error messages has always seemed to me to be utterly ingenious, whether or not it originated there. I.e., error messages are tagged with error codes that it spits out in the form of URLs, like, e.g.,

https://ipxe.org/err/040ee1

(Edit: richer example here: https://ipxe.org/err/4c1060)

When a user pulls up the link, it produces a wiki page that points right to the location in the (current) source code of iPXE where the error was spit out (which is really useful for that project because iPXE itself usually can't provide a lot of detail when it croaks, so you sometimes have to read backwards through the code).

Often much more usefully, the page has an editable portion where other users are encouraged to contribute pointers, as in the case of that ipxe.org page, where they've got almost a diagnostic key (and you don't need to step backwards through the code to try to infer the cause).

Hence, instead of cutting-and-pasting the error message text and hoping an appropriate stackoverflow answer pops up and it's not one of the other 15 ways that, say, host was unreachable, you get something with more pinpoint accuracy, like, say, (just making stuff up) it's "no route to host", so check your netmask and your gateway.

I'm imagining that the type checker or whatever is producing GHC error messages might be able to leave breadcrumbs in a URL that might trace the way that it failed, so the particular pathology it's wended its way through can lead to a more friendly diagnosis in a related error gallery, if somebody's been generous enough to describe how it was resolved in that person's case. (And then you can mine the usage data to figure out stuff about where people are running into errors that stump them, i guess. Getting even further fantastical, maybe an IDE could request some version of the URL to tell it how to walk the user through a fix, although now maybe i'm regurgitating the AI Kool-Aid. Or maybe some haskell-version upgrader could do likewise to mechanically upgrade code bases that fail to compile. Or maybe i should just shut up now and stop conjuring up privacy nightmares).

Not that i don't think stackoverflow and web search aren't otherwise pretty awesome.

And not that GHC doesn't already do an awesome job suggesting potential fixes and doing all but writing your *{-# LANGUAGE #-}` pragmas into the source file for you ... But maybe some of the work it takes for GHC to dispense that wisdom could be handed off to such a reference instead, maybe leaving it so the developers can develop and not mollycoddle us :stuck_out_tongue: . (Though, yeah, that makes it harder to work with GHC when you don't have an internet connection and/or don't want to let whoever's eavesdropping know that you're developing your killer app in Haskell, so, maybe, nah)

And thanks to anybody who's reading this who had a role in any of that. Hope this wasn't a distracting waste of the time you obviously know how to put to good use otherwise.

**Comment by noughtmare** [comment]
I have been thinking that we can already do part of this, namely collecting a knowledge-base containing further information for error messages. I have started making [a sample page in the wiki of my fork here](https://github.com/noughtmare/error-messages/wiki/Pattern-Match(es)-Are-Non-Exhaustive). 

Even if GHC error messages are not linked directly to this knowledge-base, it might still be useful to start building it. I think these pages can be found pretty easily via GitHub's built-in search (we can even include a list of keywords to make pages easier to find).

I have made my wiki pages editable by any user (I hope), so feel free to add or change things. If this sounds like a good idea then i would suggest that we make the wiki in this repository editable for non-contributors as well and then I can transfer this page to this repo and perhaps start working on other pages as well.

I would like to point out that @Yakushima has [pages about error messages on a GitHub wiki too](https://github.com/Yakushima/errors/wiki). But I think it is useful to keep opinions and suggestions in GitHub issues and have the wiki as an informative resource for Haskell users struggling with error messages. How do you feel about this? Maybe we can split your existing pages into opinions in issues and informative wiki pages?

**Comment by ketzacoatl** [comment]
Yea, this topic has recently been a bit of an ongoing discussion, across a few spaces. I agree it is a topic we should carry forward to take some sort of action on. The question is mostly about how and what that actually looks like. What is both agreeable and realistically actionable?

I think most would agree that a catalog of messages with unique URLs to some page on the internet is one of the more ideal end-results we could define for some real-world target we'd like to achieve. From the UX perspective, adding a URL to each message is relatively non-intrusive (wrt changing the text in the error message, which has more nuance and wider implications with broader impact). 

However, it is a significant effort and we need a bit of an action plan to coordinate that energy.

There is also the question of what dependencies in GHC that would have, for example it might make a lot of sense for this to depend on the structured error messages that @goldfirere has been working on. Maybe it would be acceptable to just tack a URL onto each error message, but I would guess it would be more agreeable to GHCHQ if the URL were included as a new field and applied in the same way universally.

There is also the question of where the content for the error messages live, what the URLs look like (do we use ids/tokens?), and which entity is taking responsibility for maintaining the catalog or caring about it. A wiki in a project, or some git repo, on GHCHQ's GitLab, is a pretty natural option, but maybe there are reasons that doesn't make sense or some other place is a better option.

While I don't think we should block or hold the effort to accomplish this, it's also somewhat dependent on not only building that catalog, but even just defining the entries in that catalog. To someone like myself with less experience, there are many messages I would define as separate entries whereas someone with more experience would probably see how several of my entries are just one entry in the catalog. We need an agreeable way to navigate these problems to quickly and efficiently build that catalog (and completely - it doesn't make a lot of sense to build a partial catalog that omits 75% of the content available).

Even if the results will be hosted elsewhere, this is all stuff I see as within the scope of this project, so we can feel empowered to figure out the best way to facilitate and implement all the pieces to this puzzle. For example, even if we need broader support or agreement on the catalog, we could collectively build our own version of that idea here in this repo, and use that as a demonstration and space for more discussion or refinement of the idea.

At least for me, I don't know: what is the most efficient way of building this catalog to some reasonable level of completeness? What exists in GHC (or outside) already, that would help us build the catalog? What criteria is used to decide what entries go into the catalog?

**Comment by goldfirere** [comment]
I think a very good first stab at what to address would be to look at this data type (https://gitlab.haskell.org/ghc/ghc/-/blob/20e6fec8106521efe7c571612d6d4353fec5c832/compiler/GHC/Driver/Errors/Types.hs#L66) and create a page for every constructor of the types mentioned there. This won't cover all the errors in today's GHC, because not every error has been ported over to the new format. But it would be a very good starting point. To keep track of the pages, we could even name the pages after the constructors. These aren't shown to users, but they are useful internal identifiers. If/when we create user-visible ids, it should be easy to map from these internal ids to the new external ones.

It would take only a tiny bit of support from GHC to print out the URL in the message. I would do this by adding a new `diagnosticURL :: a -> Maybe URL` (for some `URL` type... maybe just a `String` for now) to the `Diagnostic` class (https://gitlab.haskell.org/ghc/ghc/-/blob/20e6fec8106521efe7c571612d6d4353fec5c832/compiler/GHC/Types/Error.hs#L230), and then including this URL in the rendered output when available. Because it would be printed only when there really is a URL, we can build out the facility slowly.

**Comment by noughtmare** [comment]
I guess this can be closed now that [the error message index](https://discourse.haskell.org/t/announcing-the-haskell-error-index/5195?u=jaror) has been announced.

**Comment by blabzilla** [comment]
> I guess this can be closed now that [the error message index](https://discourse.haskell.org/t/announcing-the-haskell-error-index/5195?u=jaror) has been announced.

Yeah, it seems like my wish came true, with both the index and the references being put into GHC to be indexed.

Thanks to the folks working on both the references and referents and to the folks here working on all the verbiage around them.
