### ISSUE TITLE
Display -Werror messages after warnings

### ISSUE THREAD

**Issue by Innf107** [haskell/error-messages#12]
Usually when compiling a module, GHC first displays all warnings and then all errors.
This is not the case when compiling with -Werror.

Example:
```hs
f x = case x of 0 -> Just {}
```
When compiled with `-Wmissing-fields -Werror=incomplete-patterns`, this example *first* displays the error message for `-Werror=incomplete-patterns and` *then* the warning for `-Wmissing-fields`.
This means that one has to scroll up to see the error message, and especially in GHCi, it is not even immediately obvious, that the module didn't compile if there are a few warnings.

Ideally, GHC should first display all warnings and *after that* display errors, including those produced by -Werror.

**Comment by goldfirere** [comment]
Thanks for the very clear explanation!

I thought GHC always suppressed warnings when there are errors present (except for those generated by `-Werror`). Do you have an example of where it puts the warnings first? I've never seen that.

When we have both warnings and -Werrors, the warnings and errors are ordered by location in the source code. We could instead put all warnings first or all errors first when there are both, but I'd like others to chime in also to see if they would find this kind of categorization useful. (It sounds like you would.)

You may also be interested in `-freverse-errors`, which reverses the order in which GHC prints out the errors (and warnings) it has.

**Comment by Innf107** [comment]
> I thought GHC always suppressed warnings when there are errors present (except for those generated by `-Werror`). Do you have an example of where it puts the warnings first? I've never seen that.

Interesting, it seems you're right. GHC (or at least stack?) still displays warnings for other modules, so you still get the effect, that you get all warnings before any errors, although warnings in the same module are apparently suppressed.

> When we have both warnings and -Werrors, the warnings and errors are ordered by location in the source code. We could instead put all warnings first or all errors first when there are both, but I'd like others to chime in also to see if they would find this kind of categorization useful. (It sounds like you would.)

I would love that, actually.

> You may also be interested in `-freverse-errors`, which reverses the order in which GHC prints out the errors (and warnings) it has.

Wow, I'm immediately turning that on for every project. Thank you!

**Comment by goldfirere** [comment]
Upon reviewing this ticket, I'm left with the feeling that this is better handled by an IDE, not GHC itself. The warnings/errors that you initially experienced were coming from multiple invocations of GHC (by stack), and then the mixing of warnings/errors in the same module is a rare occurrence. I do see the value in what you ask, but supporting this in GHC would end up creating yet another obscure configuration flag that would need to be documented and supported into perpetuity, and I'm not yet convinced the benefit is worth the cost. On the other hand, IDEs are considerably more concerned with user interaction and the effective arrangement of error messages.

My inclination is to close the ticket, but do push back if you disagree.
