### ISSUE TITLE
Leaking information about `GHC.GHCi.ghciStepIO` in GHCi

### ISSUE THREAD

**Issue by MorrowM** [haskell/error-messages#26]
Here's a real example of an error message someone asked about.

```
ghci> thing = putStrLn -- defined higher up
ghci> :{
| thing <- getLine
| putStrLn thing
| :}
<interactive>:291:9: error:
    • Couldn't match expected type ‘(String -> IO ())
                                    -> (String -> IO ()) -> IO a0’
                  with actual type ‘IO String’
    • The function ‘getLine’ is applied to two arguments,
      but its type ‘IO String’ has none
      In the first argument of ‘GHC.GHCi.ghciStepIO ::
                                  forall a. IO a -> IO a’, namely
        ‘(getLine putStrLn thing)’
      In a stmt of an interactive GHCi command:
        thing <- GHC.GHCi.ghciStepIO :: forall a. IO a -> IO a
                 (getLine putStrLn thing)
```
1. I don't think we should be leaking this detail about `stepIO` to end users.
2. It obfuscates the real issue, that this is all being run as a single statement. The issue would be clearer if the message were:
```
    • The function ‘getLine’ is applied to two arguments,
      but its type ‘IO String’ has none
      In the expression:  getLine putStrLn thing
      In a stmt of an interactive GHCi command:
        thing <- getLine putStrLn thing
                 ```
```
Tested with GHC 8.10.7 and 9.0.1.

**Comment by goldfirere** [comment]
Yes, I agree completely. GHC should never report about `ghciStepIO` in an error message.

I think your post would be appropriate for a GHC ticket as is. It's specific and actionable, and the suggested new message should not be hard to cook up. Would you care to post to gitlab.haskell.org/ghc/ghc?

Thanks!

**Comment by MorrowM** [comment]
Made a GHC ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/20787

**Comment by MorrowM** [comment]
Seems it's a duplicate of a long-standing issue (bah, I should've checked before I made the issue): https://gitlab.haskell.org/ghc/ghc/-/issues/10249
