### ISSUE TITLE
labels for tracking issues

### ISSUE THREAD

**Issue by ketzacoatl** [haskell/error-messages#38]
As this project grows, it becomes more important to be able to filter the list of issues in various ways (in order to be able to review the different groups of issues and help push them along further). To that end, I'd like to suggest we come up with a list of labels for useful sorting/filtering of the issues.

Some obvious "states" I think we should probably have labels for:

* new, needs review
* needs more info or a better example, or some more discussion
* ready for upstream ticket
* has a ticket upstream and waiting on upstream action
* upstream needs contributor to own the change
* updates complete

What should our labels be, which states should have labels?

**Comment by goldfirere** [comment]
For me, I see the first two bullets as the same: the error message is still being constructed. (Maybe there's a separate, additional label for "needs more info".) Then, once a ticket is ready for a GHC issue to be filed, I hope we don't need a label -- let's just make the GHC issue. Then we can say that there is an unassigned GHC issue. We keep the ticket open here -- it might be enough to draw in a potential contributor who could fix the GHC issue.

To me, this suggests 3 state labels: Composing error message; GHC ticket created, unassigned; GHC ticket created, assigned. This is rather less elaborate than your proposal. Do you see advantages to having the finer-grained labeling?

**Comment by ketzacoatl** [comment]
> To me, this suggests 3 state labels: Composing error message; GHC ticket created, unassigned; GHC ticket created, assigned. This is rather less elaborate than your proposal. Do you see advantages to having the finer-grained labeling?

I agree that's a good place to start.

**Comment by ketzacoatl** [comment]
I've created those labels.
