### ISSUE TITLE
Binding representation-polymorphic values

### ISSUE THREAD

**Issue by konsumlamm** [haskell/error-messages#41]
Currently, binding a levity-polymorphic value (actually, a representation-polymorphic value) is not allowed. For example
```hs
($#) :: forall r1 r2 (a :: TYPE r1) (b :: TYPE r2). (a -> b) -> a -> b
f $# x = f x
```
produces the following error message:
```
    A levity-polymorphic type is not allowed here:
      Type: a
      Kind: TYPE r1
    In the type of binder ‘x’
```
I think it would be clearer to say that binding representation-polymorphic values in general isn't allowed, since that isn't exactly obvious from the error message.

**Comment by goldfirere** [comment]
The whole facility for detecting this case and reporting an error has been revamped, essentially from scratch. @sheaf did the heavy lifting.

The new error messages are

```
Bug.hs:8:1: error:
    The type of the second pattern in the equation for ‘$#’
    does not have a fixed runtime representation:
      a :: TYPE r1
  |
8 | f $# x = f x
  | ^^^^^^^^^^^^

Bug.hs:8:12: error:
    • The function argument
        ‘x’
      does not have a fixed runtime representation:
        a :: TYPE r1
    • In the first argument of ‘f’, namely ‘x’
      In the expression: f x
      In an equation for ‘$#’: f $# x = f x
  |
8 | f $# x = f x
  |            ^
```

And the new messages are correct: there really are *two* errors here. One is the binding for `x`. The other is the usage.

What do you think?

**Comment by konsumlamm** [comment]
Ah, that's great! I think the new error messages make this issue obsolete.
