### ISSUE TITLE
Update url

### ISSUE THREAD

**Issue by alt-romes** [haskell/error-messages#522]
The URL in the description is outdated.
The updated version is (I believe) https://haskell.foundation/error-message-index/

Perhaps we can also add it to the README?

It'd also be good to add the URL to the description of the other repository

**Comment by elland** [comment]
@alt-romes that URL means to point to the repository, not the actual index, right?

**Comment by david-christiansen** [comment]
It looks to me like it points to the right place. @alt-romes , can you be a bit more specific as to which URL you mean?

**Comment by alt-romes** [comment]
The GitHub repository description of https://github.com/haskell/error-messages points to https://haskell.github.io/error-messages/, which I think is outdated.

I think the correct link is rather https://haskell.foundation/error-message-index/ -- it points me to the index page.

**Comment by david-christiansen** [comment]
Ah, now I see it.

In fact, the right thing to do was to delete it, as this repo no longer hosts the site in question.

Thanks for noticing!
