### ISSUE TITLE
NB -> Note

### ISSUE THREAD

**Issue by Topsii** [haskell/error-messages#528]
I just looked up that NB: means nota bene.
[https://en.wikipedia.org/wiki/Nota_bene](https://en.wikipedia.org/wiki/Nota_bene)
> In Modern English, it is used, particularly in legal papers, to draw the attention of the reader to a certain (side) aspect or detail of the subject being addressed. While NB is also often used in academic writing, note is a common substitute.

I suggest to replace `NB:` with `Note:` in GHC's error messages. 

I saw NB in this recently added error message:

    • The ‘~’ operator is out of scope.
      Assuming it to stand for an equality constraint.
    • NB: ‘~’ used to be built-in syntax but now is a regular type operator
          exported from Data.Type.Equality and Prelude.
      If you are using a custom Prelude, consider re-exporting it.

Though I must have skipped it when reading errors for years. After all NB is [pervasively used in GHC's error messages](https://github.com/search?q=NB+repo%3Aghc%2Fghc+extension%3Astderr&type=Code&ref=advsearch&l=&l=). 

For me it is definitely no major issue, but it has always been another part that confuses more than it explains.

**Comment by cbrt-x** [comment]
I'll work on an implementation

**Comment by cbrt-x** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12751
