### ISSUE TITLE
Inclusion criteria

### ISSUE THREAD

**Issue by hasufell** [haskell/error-messages#540]
The readme says:

> We are interested in building a catalog of error messages for each tool in common use (GHC, Cabal, Stack, ghcup, HLS, etc)

But why limit to common tools? The idea of easily discoverable error codes goes beyond. Is this a concern of maintenance? Could there be tier3 supported projects that simply get assigned a namespace and can maintain it?

As an example, cabal-cache is currently evaluating whether to follow this scheme: https://github.com/haskell-works/cabal-cache

It's not that common (I guess), but since it's primary use case is CI, it seems very natural in terms of usability to do this. You see an error in your CI logs and can quickly jump to a page explaining it and maybe linking to workarounds.

@newhoggy

**Comment by noughtmare** [comment]
The error index project has split from this repo and moved to [haskellfoundation/error-message-index](https://github.com/haskellfoundation/error-message-index). There is now a more elaborate document for tool developers: [tool-developers.md](https://github.com/haskellfoundation/error-message-index/blob/main/tool-developers.md).

**Comment by david-christiansen** [comment]
The "catalog of error messages" here is more "here's a confusingly-phrased type error, how can we make it better" rather than "This is error number 39824". I'll take the liberty of transferring this issue from https://github.com/haskell/error-messages/ to https://github.com/haskellfoundation/error-message-index/ .

**Comment by david-christiansen** [comment]
Never mind, can't transfer between organizations. This is an unfortunate limitation in GitHub. I opened haskellfoundation/error-message-index#370 as a forum for this discussion.
