### ISSUE TITLE
There should be a `flag` field in the metadata which indicates the corresponding -Wxxx flag.

### ISSUE THREAD

**Issue by BinderDavid** [haskell/error-messages#75]
The current examples for warnings don't contain a metadata flag for the corresponding flag which has to be passed to GHC in order to enable the warning.

E.g.

```
--
ghc-flag: WmissingFields
--
```

**Comment by david-christiansen** [comment]
This was fixed in #79 , right?

**Comment by BinderDavid** [comment]
Yes, this is now fixed.
