### ISSUE TITLE
Coherency in structure

### ISSUE THREAD

**Issue by PPKFS** [haskell/error-messages#78]
Do we want to have consistency in the following ideas?

- `module Main`, `module Example`, `module SpecificToThisErrorMessage`, no module? (I personally think no module is best)
- Should we be writing ideal Haskell; i.e. with top-level signatures?
- Error messages in the index.md?

**Comment by david-christiansen** [comment]
My opinions:

 * Not having a module name is great, as long as there's no issues arising from the implicit module name being `Main` and it makes sense for the example. Some examples will require names, and I think it's best if they have plausible, meaningful names.
 * I think that we should write Haskell in a way that best illustrates the issue at hand, and is using the nicest possible conventions when it's not relevant to the example.
 * Seems like a nice thing to have
