### ISSUE TITLE
Rename this repository to reduce risk of confusion

### ISSUE THREAD

**Issue by anka-213** [haskell/error-messages#8]
As the readme notes, there is already a package named "error" and a name like "error-messages" would probably be clearer about the intent. It would also match closer to the name of the repo that inspired this one: https://github.com/elm/error-message-catalog. (As was mentioned in the thread for creating this repo: https://discourse.haskell.org/t/proposal-an-issue-tracker-for-better-error-messages/2498)

I regret not doing this bikeshed before the repo was created.

**Comment by goldfirere** [comment]
I'm fine with this suggestion. @ketzacoatl ?

**Comment by ketzacoatl** [comment]
The generality of the name `errors` is quite nice, I'm not sure we want to limit ourselves as much as `error-message-catalog` does. At the same time, I don't care enough to object.

**Comment by anka-213** [comment]
I agree that it can be nice to not limit ourselves in scope too much with the name, but I feel like `errors` is too generic to be meaningful.
If someone who is not familiar with this project sees just the url, the name `haskell/errors` doesn't say much and could mean very many different things (including the `error` package), while something like `error-messages` should give a bit more of a hint as to what this project is about.

**Comment by ketzacoatl** [comment]
My hope was that the README would clarify enough, as it seems we can never satisfy everyone all the time. Reading the intro in the README ought to clarify the purpose for the repo/project.

**Comment by goldfirere** [comment]
I see several statements in favor of the change and one statement against (but mitigated with "I don't care enough to object"). That suggests that the change is worthwhile.

For what it's worth, I agree that `error-message-catalog` is too limiting, but `error-messages` does seem to nicely fit our desired goal.

**Comment by goldfirere** [comment]
Done.

**Comment by anka-213** [comment]
@ketzacoatl The README is absolutely clear enough. My goal was to have some more clarity about what the project is even before you click the link and read the intro, which I think the new name does slightly better than the old one in my opinion.

Thanks!
